name: Generate Proto Code & Commit

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Protobuf code
        uses: bufbuild/buf-action@v1
        with:
          format: true
          lint: true
          push: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download dependencies
        run: go mod download

      - name: Injest Go Tags
        run: |
          buf dep update
          buf generate
          go install github.com/favadi/protoc-go-inject-tag@latest
          find gen -name "*.pb.go" -exec protoc-go-inject-tag -input={} \;

      - name: Start services
        run: |
          docker compose up -d --wait

      - name: Run tests
        run: go test -v ./...

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: Refresh protobuf generated files in ./gen/ and ./doc/ and buf.lock"
          commit_options: '--no-verify'
          file_pattern: 'gen/ doc/ buf.lock'
          branch: ${{ github.ref_name }}
